/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/workflow-definitions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["workflowDefinitions.list"];
    put?: never;
    post: operations["workflowDefinitions.create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workflow-definitions/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["workflowDefinitions.listByName"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workflow-definitions/{name}/v/{version}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["workflowDefinitions.get"];
    put?: never;
    post?: never;
    delete: operations["workflowDefinitions.delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workflow-definitions/{name}/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["workflowDefinitions.createVersion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workflow-executions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["workflowExecutions.list"];
    put?: never;
    post: operations["workflowExecutions.start"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workflow-executions/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["workflowExecutions.get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    DataType: "string" | "number" | "boolean" | "array" | "object";
    /** @enum {string} */
    ArrayItemType: "string" | "number" | "boolean" | "object";
    ParameterDefinition: {
      name: string;
      description?: string | null;
      dataType: components["schemas"]["DataType"];
      arrayItemType?: components["schemas"]["ArrayItemType"] | null;
      format?: string | null;
      required: boolean;
      default?: unknown | null;
    };
    ManualTriggerDefinition: {
      id: string;
      name: string;
      description?: string | null;
      /** @enum {string} */
      _type: "manual";
    };
    TriggerDefinition: components["schemas"]["ManualTriggerDefinition"];
    ForkStepDefinition: {
      id: string;
      name: string;
      description?: string | null;
      /** @enum {string} */
      _type: "fork";
    };
    /** @enum {string} */
    DecisionMode: "firstMatch" | "allMatches";
    DecisionBranchDefinition: {
      output: string;
      condition: string;
    };
    DecisionStepDefinition: {
      id: string;
      name: string;
      description?: string | null;
      /** @enum {string} */
      _type: "decision";
      mode: components["schemas"]["DecisionMode"];
      branches: components["schemas"]["DecisionBranchDefinition"][];
      defaultOutput?: string | null;
      allowMultipleMatches?: boolean | null;
    };
    /** @enum {string} */
    JoinMode: "all" | "any";
    JoinStepDefinition: {
      id: string;
      name: string;
      description?: string | null;
      /** @enum {string} */
      _type: "join";
      mode?: components["schemas"]["JoinMode"] | null;
    };
    ControlStepDefinition:
      | components["schemas"]["ForkStepDefinition"]
      | components["schemas"]["DecisionStepDefinition"]
      | components["schemas"]["JoinStepDefinition"];
    LiteralExpression: {
      /** @enum {string} */
      _type: "Literal";
      value: unknown;
    };
    WorkflowInputExpression: {
      /** @enum {string} */
      _type: "WorkflowInput";
      name: string;
    };
    TaskOutputExpression: {
      /** @enum {string} */
      _type: "TaskOutput";
      stepId: string;
      path: string[];
    };
    ValueExpression:
      | components["schemas"]["LiteralExpression"]
      | components["schemas"]["WorkflowInputExpression"]
      | components["schemas"]["TaskOutputExpression"];
    TaskRetryDefinition: {
      maxAttempts: number;
      delayMs: number | ("Infinity" | "-Infinity" | "NaN");
    };
    TaskStepDefinition: {
      id: string;
      name: string;
      description?: string | null;
      /** @enum {string} */
      _type: "task";
      taskId: string;
      inputs: {
        [key: string]: components["schemas"]["ValueExpression"];
      };
      retry?: components["schemas"]["TaskRetryDefinition"] | null;
    };
    WorkflowStepDefinition:
      | components["schemas"]["ControlStepDefinition"]
      | components["schemas"]["TaskStepDefinition"];
    WorkflowTransitionSource: {
      stepId: string;
      output?: string | null;
    };
    TransitionDefinition: {
      from: components["schemas"]["WorkflowTransitionSource"];
      to: string;
    };
    WorkflowDefinitionEntry: {
      name: string;
      description?: string | null;
      version: string;
      tags?: string[] | null;
      inputs: components["schemas"]["ParameterDefinition"][];
      outputs: components["schemas"]["ParameterDefinition"][];
      triggers: components["schemas"]["TriggerDefinition"][];
      steps: components["schemas"]["WorkflowStepDefinition"][];
      transitions: components["schemas"]["TransitionDefinition"][];
      latest: boolean;
    };
    WorkflowDefinitionNotFoundProblem: {
      /** @enum {string} */
      type: "urn:workflow-engine:problem:workflow-definition-not-found";
      /** @enum {string} */
      title: "Workflow definition not found";
      /** @enum {number} */
      status: 404;
      detail?: string | null;
      /** @enum {string} */
      code: "WORKFLOW_DEFINITION_NOT_FOUND";
      name: string;
      version?: string | null;
    };
    WorkflowDefinition: {
      name: string;
      description?: string | null;
      version: string;
      tags?: string[] | null;
      inputs: components["schemas"]["ParameterDefinition"][];
      outputs: components["schemas"]["ParameterDefinition"][];
      triggers: components["schemas"]["TriggerDefinition"][];
      steps: components["schemas"]["WorkflowStepDefinition"][];
      transitions: components["schemas"]["TransitionDefinition"][];
    };
    CreateVersionedWorkflowDefinition: {
      definition: components["schemas"]["WorkflowDefinition"];
    };
    /** @enum {string} */
    BumpType: "major" | "minor" | "patch";
    VersionBumpingOptions: {
      bump: components["schemas"]["BumpType"];
      fromVersion?: string | null;
    };
    CreateBumpedWorkflowDefinition: {
      definition: {
        name: string;
        description?: string | null;
        tags?: string[] | null;
        inputs: components["schemas"]["ParameterDefinition"][];
        outputs: components["schemas"]["ParameterDefinition"][];
        triggers: components["schemas"]["TriggerDefinition"][];
        steps: components["schemas"]["WorkflowStepDefinition"][];
        transitions: components["schemas"]["TransitionDefinition"][];
      };
      versioning: components["schemas"]["VersionBumpingOptions"];
    };
    CreateWorkflowDefinition:
      | components["schemas"]["CreateVersionedWorkflowDefinition"]
      | components["schemas"]["CreateBumpedWorkflowDefinition"];
    CreatedWorkflowDefinition: {
      name: string;
      description?: string | null;
      version: string;
      tags?: string[] | null;
      inputs: components["schemas"]["ParameterDefinition"][];
      outputs: components["schemas"]["ParameterDefinition"][];
      triggers: components["schemas"]["TriggerDefinition"][];
      steps: components["schemas"]["WorkflowStepDefinition"][];
      transitions: components["schemas"]["TransitionDefinition"][];
      latest: boolean;
    };
    WorkflowDefinitionAlreadyExistsProblem: {
      /** @enum {string} */
      type: "urn:workflow-engine:problem:workflow-definition-already-exists";
      /** @enum {string} */
      title: "Workflow definition already exists";
      /** @enum {number} */
      status: 409;
      detail?: string | null;
      /** @enum {string} */
      code: "WORKFLOW_DEFINITION_ALREADY_EXISTS";
      name: string;
      version: string;
    };
    WorkflowDefinitionVersionBumpingErrorProblem: {
      /** @enum {string} */
      type: "urn:workflow-engine:problem:workflow-definition-version-bumping-error";
      /** @enum {string} */
      title: "Workflow definition version bumping error";
      /** @enum {number} */
      status: 400;
      detail?: string | null;
      /** @enum {string} */
      code: "WORKFLOW_DEFINITION_VERSION_BUMPING_ERROR";
      message: string;
      fromVersion?: string | null;
      /** @enum {string} */
      bump: "major" | "minor" | "patch";
      cause: unknown;
    };
    WorkflowInstanceTrigger: {
      triggerId: string;
      type: string;
      payload: unknown;
    };
    JsonRecord: Record<string, never>;
    WorkflowInstanceStatus: "Pending" | "Running" | "Succeeded" | "Failed" | "Cancelled";
    WorkflowExecutionFailure: {
      message: string;
      code?: string | null;
      details?: unknown | null;
    };
    WorkflowInstance: {
      id: string;
      workflowDefinitionName: string;
      workflowDefinitionVersion: string;
      trigger?: components["schemas"]["WorkflowInstanceTrigger"] | null;
      input: components["schemas"]["JsonRecord"];
      output?: components["schemas"]["JsonRecord"] | null;
      status: components["schemas"]["WorkflowInstanceStatus"];
      createdAt: string;
      startedAt?: string | null;
      completedAt?: string | null;
      failure?: components["schemas"]["WorkflowExecutionFailure"] | null;
    };
    WorkflowExecutionPage: {
      items: components["schemas"]["WorkflowInstance"][];
      nextCursor?: string | null;
    };
    WorkflowStepInstanceStatus:
      | "Pending"
      | "Running"
      | "WaitingRetry"
      | "Succeeded"
      | "Failed"
      | "Cancelled";
    WorkflowStepInstance: {
      id: string;
      workflowInstanceId: string;
      stepId: string;
      status: components["schemas"]["WorkflowStepInstanceStatus"];
      input: components["schemas"]["JsonRecord"];
      output?: components["schemas"]["JsonRecord"] | null;
      createdAt: string;
      startedAt?: string | null;
      completedAt?: string | null;
      failure?: components["schemas"]["WorkflowExecutionFailure"] | null;
    };
    WorkflowTaskAttemptStatus: "Pending" | "Running" | "Succeeded" | "Failed" | "Cancelled";
    WorkflowTaskAttempt: {
      id: string;
      workflowStepInstanceId: string;
      number: number;
      status: components["schemas"]["WorkflowTaskAttemptStatus"];
      output?: components["schemas"]["JsonRecord"] | null;
      createdAt: string;
      scheduledAt: string;
      startedAt?: string | null;
      completedAt?: string | null;
      failure?: components["schemas"]["WorkflowExecutionFailure"] | null;
    };
    WorkflowExecutionDetails: {
      instance: components["schemas"]["WorkflowInstance"];
      steps: components["schemas"]["WorkflowStepInstance"][];
      attempts: components["schemas"]["WorkflowTaskAttempt"][];
    };
    WorkflowExecutionNotFoundProblem: {
      /** @enum {string} */
      type: "urn:workflow-engine:problem:workflow-execution-not-found";
      /** @enum {string} */
      title: "Workflow execution not found";
      /** @enum {number} */
      status: 404;
      detail?: string | null;
      /** @enum {string} */
      code: "WORKFLOW_EXECUTION_NOT_FOUND";
      id: string;
    };
    StartWorkflow: {
      name: string;
      version: string;
      input: components["schemas"]["JsonRecord"];
      trigger?: components["schemas"]["WorkflowInstanceTrigger"] | null;
    };
    StartedWorkflowInstance: {
      id: string;
      workflowDefinitionName: string;
      workflowDefinitionVersion: string;
      trigger?: components["schemas"]["WorkflowInstanceTrigger"] | null;
      input: components["schemas"]["JsonRecord"];
      output?: components["schemas"]["JsonRecord"] | null;
      status: components["schemas"]["WorkflowInstanceStatus"];
      createdAt: string;
      startedAt?: string | null;
      completedAt?: string | null;
      failure?: components["schemas"]["WorkflowExecutionFailure"] | null;
    };
    WorkflowExecutionRejectedProblem: {
      /** @enum {string} */
      type: "urn:workflow-engine:problem:workflow-execution-rejected";
      /** @enum {string} */
      title: "Workflow execution rejected";
      /** @enum {number} */
      status: 400;
      detail?: string | null;
      /** @enum {string} */
      code: "WORKFLOW_EXECUTION_REJECTED";
      field?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  "workflowDefinitions.list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowDefinitionEntry"][];
        };
      };
    };
  };
  "workflowDefinitions.create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorkflowDefinition"];
      };
    };
    responses: {
      /** @description CreatedWorkflowDefinition */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatedWorkflowDefinition"];
        };
      };
      /** @description Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["WorkflowDefinitionAlreadyExistsProblem"]
            | components["schemas"]["WorkflowDefinitionVersionBumpingErrorProblem"];
        };
      };
    };
  };
  "workflowDefinitions.listByName": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowDefinitionEntry"][];
        };
      };
      /** @description WorkflowDefinitionNotFoundProblem */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["WorkflowDefinitionNotFoundProblem"];
        };
      };
    };
  };
  "workflowDefinitions.get": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
        version: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description WorkflowDefinitionEntry */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowDefinitionEntry"];
        };
      };
      /** @description WorkflowDefinitionNotFoundProblem */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["WorkflowDefinitionNotFoundProblem"];
        };
      };
    };
  };
  "workflowDefinitions.delete": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
        version: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description <No Content> */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description WorkflowDefinitionNotFoundProblem */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["WorkflowDefinitionNotFoundProblem"];
        };
      };
    };
  };
  "workflowDefinitions.createVersion": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VersionBumpingOptions"];
      };
    };
    responses: {
      /** @description CreatedWorkflowDefinition */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatedWorkflowDefinition"];
        };
      };
      /** @description Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["WorkflowDefinitionNotFoundProblem"]
            | components["schemas"]["WorkflowDefinitionAlreadyExistsProblem"]
            | components["schemas"]["WorkflowDefinitionVersionBumpingErrorProblem"];
        };
      };
    };
  };
  "workflowExecutions.list": {
    parameters: {
      query?: {
        name?: string | null;
        cursor?: string | null;
        limit?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description WorkflowExecutionPage */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowExecutionPage"];
        };
      };
    };
  };
  "workflowExecutions.start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartWorkflow"];
      };
    };
    responses: {
      /** @description StartedWorkflowInstance */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StartedWorkflowInstance"];
        };
      };
      /** @description Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["WorkflowDefinitionNotFoundProblem"]
            | components["schemas"]["WorkflowExecutionRejectedProblem"];
        };
      };
    };
  };
  "workflowExecutions.get": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description WorkflowExecutionDetails */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowExecutionDetails"];
        };
      };
      /** @description WorkflowExecutionNotFoundProblem */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["WorkflowExecutionNotFoundProblem"];
        };
      };
    };
  };
}
