/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/workflow-definitions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["workflowDefinitions.list"];
    put?: never;
    post: operations["workflowDefinitions.create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workflow-definitions/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["workflowDefinitions.listByName"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workflow-definitions/{name}/v/{version}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["workflowDefinitions.get"];
    put?: never;
    post?: never;
    delete: operations["workflowDefinitions.delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workflow-definitions/{name}/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["workflowDefinitions.createVersion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    WorkflowDefinitionNotFoundEncoded: {
      /** @enum {string} */
      _tag: "WorkflowDefinitionNotFound";
      name: string;
      version?: string | null;
    };
    WorkflowDefinitionAlreadyExistsEncoded: {
      /** @enum {string} */
      _tag: "WorkflowDefinitionAlreadyExists";
      name: string;
      version: string;
    };
    WorkflowDefinitionVersionBumpingErrorEncoded: {
      /** @enum {string} */
      _tag: "WorkflowDefinitionVersionBumpingError";
      message: string;
      fromVersion?: string | null;
      /** @enum {string} */
      bump: "major" | "minor" | "patch";
      cause: unknown;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  "workflowDefinitions.list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            name: string;
            description?: string | null;
            version: string;
            tags?: string[] | null;
            inputs: {
              name: string;
              description?: string | null;
              /** @enum {string} */
              dataType: "string" | "number" | "boolean" | "array" | "object";
              arrayItemType?: ("string" | "number" | "boolean" | "object") | null;
              format?: string | null;
              required: boolean;
              default?: unknown | null;
            }[];
            outputs: {
              name: string;
              description?: string | null;
              /** @enum {string} */
              dataType: "string" | "number" | "boolean" | "array" | "object";
              arrayItemType?: ("string" | "number" | "boolean" | "object") | null;
              format?: string | null;
              required: boolean;
              default?: unknown | null;
            }[];
            triggers: {
              id: string;
              name: string;
              description?: string | null;
              /** @enum {string} */
              _type: "manual";
            }[];
            steps: (
              | (
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "fork";
                    }
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "decision";
                      /** @enum {string} */
                      mode: "firstMatch" | "allMatches";
                      branches: {
                        output: string;
                        condition: string;
                      }[];
                      defaultOutput?: string | null;
                      allowMultipleMatches?: boolean | null;
                    }
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "join";
                      mode?: ("all" | "any") | null;
                    }
                )
              | {
                  id: string;
                  name: string;
                  description?: string | null;
                  /** @enum {string} */
                  _type: "task";
                  taskId: string;
                  inputs: {
                    [key: string]:
                      | {
                          /** @enum {string} */
                          _type: "Literal";
                          value: unknown;
                        }
                      | {
                          /** @enum {string} */
                          _type: "WorkflowInput";
                          name: string;
                        }
                      | {
                          /** @enum {string} */
                          _type: "TaskOutput";
                          stepId: string;
                          path: string[];
                        };
                  };
                }
            )[];
            transitions: {
              from: {
                stepId: string;
                output?: string | null;
              };
              to: string;
            }[];
            latest: boolean;
          }[];
        };
      };
    };
  };
  "workflowDefinitions.create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json":
          | {
              definition: {
                name: string;
                description?: string | null;
                version: string;
                tags?: string[] | null;
                inputs: {
                  name: string;
                  description?: string | null;
                  /** @enum {string} */
                  dataType: "string" | "number" | "boolean" | "array" | "object";
                  arrayItemType?: ("string" | "number" | "boolean" | "object") | null;
                  format?: string | null;
                  required: boolean;
                  default?: unknown | null;
                }[];
                outputs: {
                  name: string;
                  description?: string | null;
                  /** @enum {string} */
                  dataType: "string" | "number" | "boolean" | "array" | "object";
                  arrayItemType?: ("string" | "number" | "boolean" | "object") | null;
                  format?: string | null;
                  required: boolean;
                  default?: unknown | null;
                }[];
                triggers: {
                  id: string;
                  name: string;
                  description?: string | null;
                  /** @enum {string} */
                  _type: "manual";
                }[];
                steps: (
                  | (
                      | {
                          id: string;
                          name: string;
                          description?: string | null;
                          /** @enum {string} */
                          _type: "fork";
                        }
                      | {
                          id: string;
                          name: string;
                          description?: string | null;
                          /** @enum {string} */
                          _type: "decision";
                          /** @enum {string} */
                          mode: "firstMatch" | "allMatches";
                          branches: {
                            output: string;
                            condition: string;
                          }[];
                          defaultOutput?: string | null;
                          allowMultipleMatches?: boolean | null;
                        }
                      | {
                          id: string;
                          name: string;
                          description?: string | null;
                          /** @enum {string} */
                          _type: "join";
                          mode?: ("all" | "any") | null;
                        }
                    )
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "task";
                      taskId: string;
                      inputs: {
                        [key: string]:
                          | {
                              /** @enum {string} */
                              _type: "Literal";
                              value: unknown;
                            }
                          | {
                              /** @enum {string} */
                              _type: "WorkflowInput";
                              name: string;
                            }
                          | {
                              /** @enum {string} */
                              _type: "TaskOutput";
                              stepId: string;
                              path: string[];
                            };
                      };
                    }
                )[];
                transitions: {
                  from: {
                    stepId: string;
                    output?: string | null;
                  };
                  to: string;
                }[];
              };
            }
          | {
              definition: {
                name: string;
                description?: string | null;
                tags?: string[] | null;
                inputs: {
                  name: string;
                  description?: string | null;
                  /** @enum {string} */
                  dataType: "string" | "number" | "boolean" | "array" | "object";
                  arrayItemType?: ("string" | "number" | "boolean" | "object") | null;
                  format?: string | null;
                  required: boolean;
                  default?: unknown | null;
                }[];
                outputs: {
                  name: string;
                  description?: string | null;
                  /** @enum {string} */
                  dataType: "string" | "number" | "boolean" | "array" | "object";
                  arrayItemType?: ("string" | "number" | "boolean" | "object") | null;
                  format?: string | null;
                  required: boolean;
                  default?: unknown | null;
                }[];
                triggers: {
                  id: string;
                  name: string;
                  description?: string | null;
                  /** @enum {string} */
                  _type: "manual";
                }[];
                steps: (
                  | (
                      | {
                          id: string;
                          name: string;
                          description?: string | null;
                          /** @enum {string} */
                          _type: "fork";
                        }
                      | {
                          id: string;
                          name: string;
                          description?: string | null;
                          /** @enum {string} */
                          _type: "decision";
                          /** @enum {string} */
                          mode: "firstMatch" | "allMatches";
                          branches: {
                            output: string;
                            condition: string;
                          }[];
                          defaultOutput?: string | null;
                          allowMultipleMatches?: boolean | null;
                        }
                      | {
                          id: string;
                          name: string;
                          description?: string | null;
                          /** @enum {string} */
                          _type: "join";
                          mode?: ("all" | "any") | null;
                        }
                    )
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "task";
                      taskId: string;
                      inputs: {
                        [key: string]:
                          | {
                              /** @enum {string} */
                              _type: "Literal";
                              value: unknown;
                            }
                          | {
                              /** @enum {string} */
                              _type: "WorkflowInput";
                              name: string;
                            }
                          | {
                              /** @enum {string} */
                              _type: "TaskOutput";
                              stepId: string;
                              path: string[];
                            };
                      };
                    }
                )[];
                transitions: {
                  from: {
                    stepId: string;
                    output?: string | null;
                  };
                  to: string;
                }[];
              };
              versioning: {
                /** @enum {string} */
                bump: "major" | "minor" | "patch";
                fromVersion?: string | null;
              };
            };
      };
    };
    responses: {
      /** @description Success */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            name: string;
            description?: string | null;
            version: string;
            tags?: string[] | null;
            inputs: {
              name: string;
              description?: string | null;
              /** @enum {string} */
              dataType: "string" | "number" | "boolean" | "array" | "object";
              arrayItemType?: ("string" | "number" | "boolean" | "object") | null;
              format?: string | null;
              required: boolean;
              default?: unknown | null;
            }[];
            outputs: {
              name: string;
              description?: string | null;
              /** @enum {string} */
              dataType: "string" | "number" | "boolean" | "array" | "object";
              arrayItemType?: ("string" | "number" | "boolean" | "object") | null;
              format?: string | null;
              required: boolean;
              default?: unknown | null;
            }[];
            triggers: {
              id: string;
              name: string;
              description?: string | null;
              /** @enum {string} */
              _type: "manual";
            }[];
            steps: (
              | (
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "fork";
                    }
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "decision";
                      /** @enum {string} */
                      mode: "firstMatch" | "allMatches";
                      branches: {
                        output: string;
                        condition: string;
                      }[];
                      defaultOutput?: string | null;
                      allowMultipleMatches?: boolean | null;
                    }
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "join";
                      mode?: ("all" | "any") | null;
                    }
                )
              | {
                  id: string;
                  name: string;
                  description?: string | null;
                  /** @enum {string} */
                  _type: "task";
                  taskId: string;
                  inputs: {
                    [key: string]:
                      | {
                          /** @enum {string} */
                          _type: "Literal";
                          value: unknown;
                        }
                      | {
                          /** @enum {string} */
                          _type: "WorkflowInput";
                          name: string;
                        }
                      | {
                          /** @enum {string} */
                          _type: "TaskOutput";
                          stepId: string;
                          path: string[];
                        };
                  };
                }
            )[];
            transitions: {
              from: {
                stepId: string;
                output?: string | null;
              };
              to: string;
            }[];
            latest: boolean;
          };
        };
      };
      /** @description Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["WorkflowDefinitionAlreadyExistsEncoded"]
            | components["schemas"]["WorkflowDefinitionVersionBumpingErrorEncoded"];
        };
      };
    };
  };
  "workflowDefinitions.listByName": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            name: string;
            description?: string | null;
            version: string;
            tags?: string[] | null;
            inputs: {
              name: string;
              description?: string | null;
              /** @enum {string} */
              dataType: "string" | "number" | "boolean" | "array" | "object";
              arrayItemType?: ("string" | "number" | "boolean" | "object") | null;
              format?: string | null;
              required: boolean;
              default?: unknown | null;
            }[];
            outputs: {
              name: string;
              description?: string | null;
              /** @enum {string} */
              dataType: "string" | "number" | "boolean" | "array" | "object";
              arrayItemType?: ("string" | "number" | "boolean" | "object") | null;
              format?: string | null;
              required: boolean;
              default?: unknown | null;
            }[];
            triggers: {
              id: string;
              name: string;
              description?: string | null;
              /** @enum {string} */
              _type: "manual";
            }[];
            steps: (
              | (
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "fork";
                    }
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "decision";
                      /** @enum {string} */
                      mode: "firstMatch" | "allMatches";
                      branches: {
                        output: string;
                        condition: string;
                      }[];
                      defaultOutput?: string | null;
                      allowMultipleMatches?: boolean | null;
                    }
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "join";
                      mode?: ("all" | "any") | null;
                    }
                )
              | {
                  id: string;
                  name: string;
                  description?: string | null;
                  /** @enum {string} */
                  _type: "task";
                  taskId: string;
                  inputs: {
                    [key: string]:
                      | {
                          /** @enum {string} */
                          _type: "Literal";
                          value: unknown;
                        }
                      | {
                          /** @enum {string} */
                          _type: "WorkflowInput";
                          name: string;
                        }
                      | {
                          /** @enum {string} */
                          _type: "TaskOutput";
                          stepId: string;
                          path: string[];
                        };
                  };
                }
            )[];
            transitions: {
              from: {
                stepId: string;
                output?: string | null;
              };
              to: string;
            }[];
            latest: boolean;
          }[];
        };
      };
      /** @description WorkflowDefinitionNotFound */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowDefinitionNotFoundEncoded"];
        };
      };
    };
  };
  "workflowDefinitions.get": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
        version: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            name: string;
            description?: string | null;
            version: string;
            tags?: string[] | null;
            inputs: {
              name: string;
              description?: string | null;
              /** @enum {string} */
              dataType: "string" | "number" | "boolean" | "array" | "object";
              arrayItemType?: ("string" | "number" | "boolean" | "object") | null;
              format?: string | null;
              required: boolean;
              default?: unknown | null;
            }[];
            outputs: {
              name: string;
              description?: string | null;
              /** @enum {string} */
              dataType: "string" | "number" | "boolean" | "array" | "object";
              arrayItemType?: ("string" | "number" | "boolean" | "object") | null;
              format?: string | null;
              required: boolean;
              default?: unknown | null;
            }[];
            triggers: {
              id: string;
              name: string;
              description?: string | null;
              /** @enum {string} */
              _type: "manual";
            }[];
            steps: (
              | (
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "fork";
                    }
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "decision";
                      /** @enum {string} */
                      mode: "firstMatch" | "allMatches";
                      branches: {
                        output: string;
                        condition: string;
                      }[];
                      defaultOutput?: string | null;
                      allowMultipleMatches?: boolean | null;
                    }
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "join";
                      mode?: ("all" | "any") | null;
                    }
                )
              | {
                  id: string;
                  name: string;
                  description?: string | null;
                  /** @enum {string} */
                  _type: "task";
                  taskId: string;
                  inputs: {
                    [key: string]:
                      | {
                          /** @enum {string} */
                          _type: "Literal";
                          value: unknown;
                        }
                      | {
                          /** @enum {string} */
                          _type: "WorkflowInput";
                          name: string;
                        }
                      | {
                          /** @enum {string} */
                          _type: "TaskOutput";
                          stepId: string;
                          path: string[];
                        };
                  };
                }
            )[];
            transitions: {
              from: {
                stepId: string;
                output?: string | null;
              };
              to: string;
            }[];
            latest: boolean;
          };
        };
      };
      /** @description WorkflowDefinitionNotFound */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowDefinitionNotFoundEncoded"];
        };
      };
    };
  };
  "workflowDefinitions.delete": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
        version: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description <No Content> */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description WorkflowDefinitionNotFound */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowDefinitionNotFoundEncoded"];
        };
      };
    };
  };
  "workflowDefinitions.createVersion": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @enum {string} */
          bump: "major" | "minor" | "patch";
          fromVersion?: string | null;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            name: string;
            description?: string | null;
            version: string;
            tags?: string[] | null;
            inputs: {
              name: string;
              description?: string | null;
              /** @enum {string} */
              dataType: "string" | "number" | "boolean" | "array" | "object";
              arrayItemType?: ("string" | "number" | "boolean" | "object") | null;
              format?: string | null;
              required: boolean;
              default?: unknown | null;
            }[];
            outputs: {
              name: string;
              description?: string | null;
              /** @enum {string} */
              dataType: "string" | "number" | "boolean" | "array" | "object";
              arrayItemType?: ("string" | "number" | "boolean" | "object") | null;
              format?: string | null;
              required: boolean;
              default?: unknown | null;
            }[];
            triggers: {
              id: string;
              name: string;
              description?: string | null;
              /** @enum {string} */
              _type: "manual";
            }[];
            steps: (
              | (
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "fork";
                    }
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "decision";
                      /** @enum {string} */
                      mode: "firstMatch" | "allMatches";
                      branches: {
                        output: string;
                        condition: string;
                      }[];
                      defaultOutput?: string | null;
                      allowMultipleMatches?: boolean | null;
                    }
                  | {
                      id: string;
                      name: string;
                      description?: string | null;
                      /** @enum {string} */
                      _type: "join";
                      mode?: ("all" | "any") | null;
                    }
                )
              | {
                  id: string;
                  name: string;
                  description?: string | null;
                  /** @enum {string} */
                  _type: "task";
                  taskId: string;
                  inputs: {
                    [key: string]:
                      | {
                          /** @enum {string} */
                          _type: "Literal";
                          value: unknown;
                        }
                      | {
                          /** @enum {string} */
                          _type: "WorkflowInput";
                          name: string;
                        }
                      | {
                          /** @enum {string} */
                          _type: "TaskOutput";
                          stepId: string;
                          path: string[];
                        };
                  };
                }
            )[];
            transitions: {
              from: {
                stepId: string;
                output?: string | null;
              };
              to: string;
            }[];
            latest: boolean;
          };
        };
      };
      /** @description Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["WorkflowDefinitionNotFoundEncoded"]
            | components["schemas"]["WorkflowDefinitionAlreadyExistsEncoded"]
            | components["schemas"]["WorkflowDefinitionVersionBumpingErrorEncoded"];
        };
      };
    };
  };
}
